const landingKinds=new Set(["hire-landing","site-landing","nara-landing","gona-landing","nadi-landing"]);
export const isFullLandingKind=(kind:string)=>landingKinds.has(kind);

function PreviewHire(){return <div className="landing-preview preview-hire"><header><b>hirewise</b><span>FOR FOCUSED INTERVIEW TEAMS</span><i>BOOK A WALKTHROUGH ↗</i></header><main><small>FROM FIRST SLOT TO FINAL DECISION</small><h2>Make room<br/>for a better<br/><em>interview.</em></h2><div className="ph-runway"><div className="ph-candidate"><span>TUE / 10:30 WAT</span><b>Amina Bello</b><small>Portfolio interview · 45 minutes</small></div><ol><li className="done"><i>01</i><b>SCHEDULE</b></li><li className="done"><i>02</i><b>PREPARE</b></li><li className="live"><i>03</i><b>MEET</b></li><li><i>04</i><b>DECIDE</b></li></ol><footer><span>3 PANELISTS READY</span><strong>10:30</strong></footer></div></main></div>}
function PreviewSite(){return <div className="landing-preview preview-site"><header><b>SiteCheck.</b><span>FIELD → REPORT → REPAIR</span><i>REQUEST DEMO</i></header><main><span className="ps-number">SC<br/>042</span><small>PROPERTY CONDITION / JAHI</small><h2>Evidence<br/>that knows<br/><em>where it came from.</em></h2><div className="ps-register"><b>18 AREAS CHECKED</b><span>14 COMPLETE</span><span>04 ISSUES</span><span>12 FILES</span></div><footer>CAPTURED ON SITE · READY FOR REPORT</footer></main></div>}
function PreviewNara(){return <div className="landing-preview preview-nara"><header><b>nara°</b><span>READ-ONLY MONEY VIEW</span><i>JOIN PRIVATE BETA</i></header><main><small>YOUR COMPLETE POSITION</small><div className="pn-ring"><b>₦3.64m</b><span>4 linked accounts</span></div><h2>One honest<br/>picture of<br/><em>your money.</em></h2><footer><span>AVAILABLE · ₦438K</span><span>INVESTED · ₦3.21M</span><span>TRANSFERS RECONCILED</span></footer></main></div>}
function PreviewRoam(){return <div className="landing-preview preview-roam"><header><b>roam</b><span>OUR TOKYO · 12—21 OCT</span><i>4 FRIENDS</i></header><main><small>NEXT TRIP / 44 DAYS</small><h2>Tokyo,<br/><em>properly shared.</em></h2><div className="pr-postcard"><b>13</b><span>GINZA<br/><small>4 places · vote closes tonight</small></span><i>→</i></div><div className="pr-stamps"><span>9 NIGHTS</span><span>¥180K EACH</span><span>3 OPEN DECISIONS</span></div></main></div>}
function PreviewGona(){return <div className="landing-preview preview-gona"><header><b>GONA</b><span>WET SEASON / MAIZE</span><i>START A SEASON ↗</i></header><main><small>ONE SEASON / ONE WORKING RECORD</small><h2>Know what<br/>is growing.</h2><div className="pg-fields"><i>F08<small>VISIT DUE</small></i><i>F12<small>READY</small></i><i>F17<small>WATCH</small></i><i>F22<small>PLANNED</small></i></div><footer><b>41 ACTIVE FIELDS</b><b>06 HARVEST LOTS</b><b>OFFLINE READY</b></footer></main></div>}
function PreviewNadi(){return <div className="landing-preview preview-nadi"><header><b>nadi<small>care passport</small></b><span>FAMILY-CONTROLLED</span><i>REQUEST ACCESS</i></header><main><small>CARE INFORMATION THAT ARRIVES WITH THE CHILD</small><h2>One current story.<br/><em>Shared with care.</em></h2><div className="pd-pass"><div><span>CARE PASSPORT / CURRENT</span><b>Zainab A.</b><small>School pass expires in 12 days</small></div><i>PASS 02</i></div><footer>HOME · SCHOOL · CLINIC</footer></main></div>}
function PreviewTold(){return <div className="landing-preview preview-told"><header><b>TOLD</b><span>PRIVATE FAMILY ARCHIVE</span><i>BEGIN AN ARCHIVE</i></header><main><small>STORY 031 / HOME</small><h2>Keep the voice.<br/><em>Keep what it meant.</em></h2><div className="pt-wave">{[22,48,31,62,39,76,28,57,44,70,35,53].map((h,i)=><i key={i} style={{height:h}}/>)}</div><footer><b>THE BLUE HOUSE IN KANO</b><span>Aunty Rabi · 18:42</span></footer></main></div>}

export function LandingPreview({slug}:{slug:string}){
 if(slug==="hirewise")return <PreviewHire/>;
 if(slug==="sitecheck")return <PreviewSite/>;
 if(slug==="nara")return <PreviewNara/>;
 if(slug==="roam")return <PreviewRoam/>;
 if(slug==="gona")return <PreviewGona/>;
 if(slug==="nadi")return <PreviewNadi/>;
 return <PreviewTold/>;
}

function HireLanding(){return <div className="full-landing fl-hire">
 <header><b>hirewise</b><nav>Why Hirewise&nbsp;&nbsp; The interview room&nbsp;&nbsp; Candidate care</nav><button>Book a walkthrough ↗</button></header>
 <section className="flh-hero"><small>INTERVIEWS, HELD TOGETHER</small><h2>Good hiring needs<br/>a proper <em>room.</em></h2><p>Schedule the people. Prepare the panel. Run the conversation. Keep the evidence together.</p><button>See the workspace →</button><div className="flh-stage"><article><span>TUE / 10:30 WAT</span><b>Amina Bello</b><small>Portfolio interview · 45 min</small></article><div><i>MS</i><i>AO</i><i>HK</i><b>3 / 3 READY</b></div></div></section>
 <section className="flh-strip"><span>01 FIND A SHARED TIME</span><span>02 PREPARE THE PANEL</span><span>03 RUN THE INTERVIEW</span><span>04 COMPARE THE EVIDENCE</span></section>
 <section className="flh-gap"><div><small>THE REAL PROBLEM</small><h3>The interview is one meeting.<br/>The work around it is scattered.</h3></div><div className="flh-gap-list"><article><b>BEFORE</b><p>Calendar threads, missing briefs and panelists arriving with different context.</p></article><article><b>DURING</b><p>The call is open in one window while questions, notes and evidence live elsewhere.</p></article><article><b>AFTER</b><p>Feedback arrives late, in different formats, after people have influenced each other.</p></article></div></section>
 <section className="flh-room"><header><small>THE INTERVIEW ROOM</small><h3>Keep the question and the evidence beside the conversation.</h3></header><div className="flh-room-ui"><div className="flh-video"><i>AB</i><span>AMINA BELLO / SPEAKING</span></div><aside><small>QUESTION 03 / 06</small><b>Tell us about a decision you changed after user feedback.</b><label>PRIVATE EVIDENCE</label><p>Amina explained why the first navigation model failed during testing…</p><button>Save & next →</button></aside></div></section>
 <section className="flh-two"><article><small>FOR THE PANEL</small><h3>Read the same brief.<br/>Score independently.</h3><div><span>Brief opened</span><b>3 / 3</b><span>Questions assigned</span><b>6 / 6</b><span>Evidence submitted</span><b>2 / 3</b></div></article><article><small>FOR THE CANDIDATE</small><h3>No hunting through old emails.</h3><p>Time, format, panel details and preparation guidance sit on one calm page.</p><button>Open candidate space ↗</button></article></section>
 <section className="flh-close"><small>A BETTER HANDOFF AT EVERY STAGE</small><h3>Run the interview.<br/>Lose the chaos.</h3><button>Book a walkthrough ↗</button></section>
 <footer><b>hirewise</b><span>Product&nbsp;&nbsp; Candidate care&nbsp;&nbsp; Privacy</span><span>INTERVIEW OPERATIONS CONCEPT / 2026</span></footer>
 </div>}

function SiteLanding(){return <div className="full-landing fl-site">
 <header><b>SiteCheck.</b><nav>FIELD TOOL / REPORTS / REPAIR LOG</nav><button>REQUEST DEMO ↗</button></header>
 <section className="fls-hero"><span className="fls-code">SC—042<br/>JAHI / ABUJA</span><small>PROPERTY CONDITION / WITHOUT THE GUESSWORK</small><h2>Capture the issue<br/><em>where it happens.</em></h2><p>Inspection evidence, condition reports and repair history in one field-to-office record.</p><button>SEE THE WORKFLOW →</button><div className="fls-scan"><span>AREA 03 / KITCHEN</span><b>PLUMBING</b><i>ISSUE · 2 PHOTOS</i></div></section>
 <section className="fls-register"><header><small>LIVE INSPECTION / SC—042</small><b>14 OF 18 AREAS COMPLETE</b></header>{[["01","Living spaces","COMPLETE","4/4"],["02","Bedrooms","COMPLETE","5/5"],["03","Kitchen","ISSUE","3/5"],["04","Exterior","OPEN","2/4"]].map((x,i)=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em className={i===2?"warn":""}>{x[2]}</em><strong>{x[3]}</strong></article>)}</section>
 <section className="fls-route"><div><small>THE RECORD BUILDS AS THE OFFICER MOVES</small><h3>One capture.<br/>Three useful outputs.</h3></div><ol><li><b>01</b><span>FIELD EVIDENCE</span><p>The area, check, note and photo stay attached.</p></li><li><b>02</b><span>CLIENT REPORT</span><p>Completed checks become the first report draft.</p></li><li><b>03</b><span>REPAIR RECORD</span><p>Owner, due date and verification remain visible.</p></li></ol></section>
 <section className="fls-report"><div className="fls-sheet"><header><span>PROPERTY CONDITION REPORT</span><b>SC—042</b></header><h3>Jahi residence</h3><div><article><b>18</b><span>AREAS CHECKED</span></article><article><b>04</b><span>ISSUES FOUND</span></article><article><b>02</b><span>ACTIONS REQUIRED</span></article></div><footer>OVERALL CONDITION <b>GOOD</b></footer></div><aside><small>THE REPORT IS NOT RETYPED</small><h3>The work done on-site is already organised.</h3><p>Back at the office, the property officer reviews the record, adds the summary and shares it.</p></aside></section>
 <section className="fls-repair"><small>FROM ISSUE TO VERIFIED REPAIR</small><div><span>RECORDED</span><i>→</i><span>ASSIGNED</span><i>→</i><span>REPAIRED</span><i>→</i><span>VERIFIED</span></div><p>Every status keeps the original evidence and the person responsible.</p></section>
 <footer><h3>Leave the property with the report already taking shape.</h3><button>REQUEST A SITECHECK DEMO ↗</button><div><b>SiteCheck.</b><span>FIELD-FIRST PROPERTY OPERATIONS / 2026</span></div></footer>
 </div>}

function NaraLanding(){return <div className="full-landing fl-nara">
 <header><b>nara°</b><nav>Position&nbsp;&nbsp; Cash flow&nbsp;&nbsp; Goals&nbsp;&nbsp; Privacy</nav><button>Join the private beta</button></header>
 <section className="fln-hero"><small>ONE READ-ONLY VIEW</small><h2>See all your money<br/>without moving <em>any of it.</em></h2><p>Nara brings savings, investments and everyday balances into one honest position.</p><div className="fln-total"><span>COMPLETE POSITION</span><b>₦3,648,200</b><small>Across 4 linked accounts · updated today</small><i>↑ 8.4% this month</i></div><button>See how the position works →</button></section>
 <section className="fln-answers"><header><small>NUMBERS THAT ANSWER SOMETHING</small><h3>The total comes first.<br/>The explanation stays close.</h3></header><div><article><span>AVAILABLE</span><b>₦438k</b><small>12% of complete position</small></article><article><span>INVESTED</span><b>₦3.21m</b><small>88% of complete position</small></article><article><span>COMMITTED</span><b>₦186k</b><small>Already assigned to goals</small></article></div></section>
 <section className="fln-flow"><div><small>CASH FLOW / AUGUST</small><h3>Transfers between your own accounts should not look like spending.</h3><p>Nara reconciles linked-account transfers before showing what actually came in and went out.</p></div><div className="fln-waterfall"><span>INCOME<b>₦640k</b></span><i className="up"/><span>OWN TRANSFERS<b>₦220k</b></span><i className="flat"/><span>SPENDING<b>₦381k</b></span><i className="down"/><span>KEPT<b>₦259k</b></span></div></section>
 <section className="fln-insight"><span>THE NOTE</span><h3>You added more to your future than you spent on your present this month.</h3><div><p>Based on 4 linked accounts</p><p>Internal transfers removed</p><p>3 records need review</p></div><button>See the working →</button></section>
 <section className="fln-goal"><header><small>GOAL LAB</small><h3>Try the change<br/>before saving it.</h3></header><div><span>HOME DEPOSIT</span><b>₦4.2m</b><div className="fln-slider"><i/></div><p>Raise the monthly amount from ₦180k to ₦220k</p><strong>New target: February 2027</strong></div></section>
 <section className="fln-private"><small>THE BOUNDARY</small><h3>Read-only means Nara can organise the picture. It cannot move the money.</h3><div><span>NO TRANSFERS</span><span>NO PAYMENTS</span><span>REVOKE ACCESS ANY TIME</span></div></section>
 <footer><b>nara°</b><h3>All the money.<br/>One honest picture.</h3><button>Join the private beta →</button><span>READ-ONLY FINANCE CONCEPT / 2026</span></footer>
 </div>}

function GonaLanding(){return <div className="full-landing fl-gona">
 <header><b>GONA<small>/ SEASON 26</small></b><nav>SEASON&nbsp;&nbsp; FIELD WORK&nbsp;&nbsp; LOTS&nbsp;&nbsp; BUYERS</nav><button>START A SEASON ↗</button></header>
 <section className="flg-hero"><small>FROM FIELD NOTE TO BUYER LOT</small><h2>Know what is growing.<br/><em>Know where it is going.</em></h2><p>One operating record for cooperatives planning the season, visiting fields and moving the harvest.</p><button>SEE GONA IN THE FIELD →</button><div className="flg-fieldboard">{[["F08","VISIT DUE"],["F12","READY"],["F17","WATCH"],["F22","PLANNED"],["F31","READY"],["F35","VISIT DUE"]].map((x,i)=><i className={`f${i}`} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></i>)}</div></section>
 <section className="flg-season"><header><span>WET SEASON / MAIZE</span><b>41 ACTIVE FIELDS</b><b>06 HARVEST LOTS</b></header><div className="flg-line"><article><span>01</span><h3>PLAN</h3><p>Fields, owners and machinery slots share one season map.</p></article><article><span>02</span><h3>VISIT</h3><p>Notes and photographs save on the device when signal disappears.</p></article><article><span>03</span><h3>GRADE</h3><p>Several farms become one traceable, buyer-ready lot.</p></article><article><span>04</span><h3>MOVE</h3><p>Load counts and collection proof close the handoff.</p></article></div></section>
 <section className="flg-offline"><div className="flg-device"><header><b>FIELD 08</b><span>NO SIGNAL</span></header><strong>VISIT SAVED</strong><p>2 notes · 1 photo<br/>Stored on this device</p><button>SYNC WHEN ONLINE</button></div><div><small>BUILT FOR THE ACTUAL FIELD</small><h3>The signal can disappear.<br/>The record cannot.</h3><p>Field mode uses large controls, clear sync language and only the checks needed during the visit.</p></div></section>
 <section className="flg-lot"><header><small>BUYER-READY LOT / GM—06—2408</small><h3>Yellow maize<br/>Grade A</h3></header><div className="flg-bags"><b>186</b><span>BAGS<br/>9,300 KG</span></div><div className="flg-checks"><span>MOISTURE <b>13.2%</b></span><span>CONTRIBUTING FARMS <b>12</b></span><span>COLLECTION <b>31 AUG</b></span></div><footer>QUALITY RECORD COMPLETE <b>READY</b></footer></section>
 <section className="flg-close"><small>ONE SEASON / ONE SHARED PICTURE</small><h3>Plan the work.<br/>Keep the proof.<br/>Move the harvest.</h3><button>START A GONA SEASON ↗</button></section>
 <footer><b>GONA</b><span>COOPERATIVE OPERATIONS CONCEPT / 2026</span><span>OFFLINE FIRST · FIELD LED</span></footer>
 </div>}

function NadiLanding(){return <div className="full-landing fl-nadi">
 <header><b>nadi<small>care passport</small></b><nav>Families&nbsp;&nbsp; Schools&nbsp;&nbsp; Care teams&nbsp;&nbsp; Privacy</nav><button>Request early access</button></header>
 <section className="fld-hero"><small>A CURRENT CARE STORY THAT CAN TRAVEL</small><h2>One child.<br/>Fewer retellings.</h2><p>Nadi helps families share the right care information with a school or clinic—without opening the whole record.</p><button>See how access works →</button><div className="fld-orbit"><i>HOME</i><i>SCHOOL</i><i>CLINIC</i><article><span>CARE PASSPORT / CURRENT</span><b>Zainab A.</b><small>Last reviewed 24 August</small><strong>PASS 02</strong></article></div></section>
 <section className="fld-why"><div><small>THE HANDOFF PROBLEM</small><h3>A parent should not have to rebuild the same care story at every door.</h3></div><p>Important details are repeated from memory during school enrolment, appointments and urgent care. Nadi keeps a current, family-controlled version ready for each handoff.</p></section>
 <section className="fld-roles"><article><span>01 / FAMILY</span><h3>One calm place to keep the current plan.</h3><p>Contacts, next visit, documents and recent events are understandable without reading a clinical chart.</p></article><article><span>02 / SCHOOL</span><h3>A limited pass with an expiry date.</h3><p>The parent chooses what the school can see. Visit history and private documents stay closed.</p></article><article><span>03 / CLINIC</span><h3>A short handoff before the appointment.</h3><p>Recent events, uploaded letters and the family&apos;s open questions arrive together.</p></article></section>
 <section className="fld-access"><header><small>SCHOOL PASS / ACCESS REVIEW</small><h3>Useful information.<br/>A deliberately small window.</h3></header><div>{[["Care contacts","SHARED"],["Everyday guidance","SHARED"],["Visit timeline","PRIVATE"],["Uploaded documents","PRIVATE"]].map((x,i)=><p key={x[0]}><i className={i<2?"on":""}>{i<2?"✓":""}</i><b>{x[0]}</b><span>{x[1]}</span></p>)}<footer>PASS EXPIRES · 10 SEPTEMBER 2026</footer></div></section>
 <section className="fld-visit"><div><small>BEFORE THE APPOINTMENT</small><h3>Bring the week into the room.</h3><p>Two recent events and one family question are prepared for the care team. Nadi records; it does not diagnose.</p></div><aside><span>FAMILY QUESTION</span><blockquote>“What should the school know before sports day next month?”</blockquote><b>READY FOR REVIEW →</b></aside></section>
 <section className="fld-private"><small>PRIVATE BY DESIGN</small><h3>The family controls every pass.</h3><div><span>Choose what is shared</span><span>Set an expiry date</span><span>Revoke access</span><span>See who opened it</span></div></section>
 <footer><b>nadi</b><h3>Share what helps.<br/>Keep the rest private.</h3><button>Request early access →</button><span>NON-DIAGNOSTIC CARE COORDINATION CONCEPT / 2026</span></footer>
 </div>}

export function ProjectLanding({slug}:{slug:string}){
 if(slug==="hirewise")return <HireLanding/>;
 if(slug==="sitecheck")return <SiteLanding/>;
 if(slug==="nara")return <NaraLanding/>;
 if(slug==="gona")return <GonaLanding/>;
 return <NadiLanding/>;
}
