import Link from "next/link";
import {projects} from "./project-data";
import {ProductMock} from "./ui-mockups";

const Arrow=()=> <span aria-hidden="true">↗︎</span>;

export default function Home(){return <main>
  <header className="site-header shell" id="top"><Link className="wordmark" href="/">MS<span>.</span></Link><nav aria-label="Primary navigation"><a href="#work">Work</a><a href="#approach">Approach</a><a href="#about">About</a><a className="nav-cta" href="mailto:muhammadmaryam831@gmail.com">Let’s talk <Arrow/></a></nav></header>
  <section className="hero shell"><div className="eyebrow"><span className="status-dot"/> Abuja, Nigeria · Available for UI/UX roles</div><h1>I make complex products feel <em>clear, useful</em> and human.</h1><div className="hero-bottom"><p>I’m Maryam Shehu Muhammad, a UI/UX designer and brand builder. I take complicated ideas and turn them into products that feel considered, useful and easy to move through.</p><div className="hero-links"><a href="#work">Explore selected work ↓</a><a href="mailto:muhammadmaryam831@gmail.com">Email me ↗</a></div></div></section>
  <section className="work shell" id="work"><div className="section-heading"><div className="section-heading-title"><p>Selected work</p><small>Click on project to view more</small></div><span>Nine independent product explorations · 2026</span></div><div className="project-list">{projects.map(project=><article className={`project-card ${project.theme}`} key={project.slug}><div className="project-copy"><div><p className="project-index">{project.number} / {project.category}</p><h2>{project.name}</h2><p className="project-tagline">{project.tagline}</p></div><div><p className="project-summary">{project.summary}</p><div className="project-meta"><span>{project.platform}</span><span>{project.role}</span><span>{project.year}</span></div><Link className="case-link" href={`/work/${project.slug}`}>View full case study <Arrow/></Link></div></div><Link href={`/work/${project.slug}`} className="project-cover" aria-label={`View ${project.name} case study`}><div className="cover-label"><span>{project.name}</span><span>{project.screens.length===1?"Full landing page":`${project.screens.length} key screens`}</span></div><div className="cover-mock"><ProductMock project={project}/></div><span className="cover-arrow">↗︎</span></Link></article>)}</div></section>
  <section className="approach shell" id="approach"><div className="section-heading"><p>How I work</p><span>Flow first. Polish second.</span></div><div className="approach-intro"><h2>I don’t start with the screens.</h2><p>I start by working out what is confusing, what is missing and what somebody is actually trying to do. The flow comes first. The visual system comes after.</p></div><div className="approach-grid">{[["01","Find the actual problem","I look past the first complaint and map where the process begins to fall apart."],["02","Work out the flow","Before I polish anything, I decide what information is needed and when."],["03","Give the product its own voice","The type, colour and interaction style should fit the product—not my other case studies."],["04","Show the decisions","A final screen means more when the reasoning and trade-offs are visible."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="about shell" id="about"><div className="section-heading"><p>About</p><span>Products with presence</span></div><div className="about-grid"><h2>I shape the product and the world around it.</h2><div><p>I’m a UI/UX designer and brand builder based in Abuja. I work where product thinking meets visual identity—designing useful digital experiences and giving brands a clear, memorable point of view.</p><p>My background makes me especially interested in operational products: tools that organise real work, reduce ambiguity and help people act with confidence.</p><div className="skills"><span>Product design</span><span>Interface design</span><span>User flows</span><span>Brand building</span><span>Visual identity</span><span>Prototyping</span><span>Design systems</span><span>Figma</span></div></div></div></section>
  <footer id="contact"><div className="shell contact-inner"><p>Have a product that needs clarity?</p><h2>Let’s make it easier to use.</h2><div className="contact-list"><a href="mailto:muhammadmaryam831@gmail.com"><small>EMAIL</small><span>muhammadmaryam831@gmail.com</span><Arrow/></a><a href="tel:+2349020280654"><small>PHONE</small><span>090 2028 0654</span><Arrow/></a><a href="https://www.linkedin.com/in/maryam-shehu-muhammad-88789427b" target="_blank" rel="noreferrer"><small>LINKEDIN</small><span>Maryam Shehu Muhammad</span><Arrow/></a></div><div className="footer-row"><span>© 2026 Maryam Shehu Muhammad</span><span>UI/UX Designer · Abuja, Nigeria</span><a href="#top">Back to top ↑</a></div></div></footer>
</main>}
