const Arrow = () => <span aria-hidden="true">↗</span>;

const ProjectInfo = ({number, type, title, description, tags, link}:{number:string;type:string;title:string;description:string;tags:string[];link?:string}) => (
  <div className="project-copy">
    <p className="project-index">{number} / {type}</p>
    <div className="project-title"><h2>{title}</h2><span>{number}</span></div>
    <p className="project-summary">{description}</p>
    <div className="tags">{tags.map(tag => <span key={tag}>{tag}</span>)}</div>
    {link ? <a href={link} className="case-link">Explore case study <Arrow /></a> : <span className="concept-label">Independent product concept</span>}
  </div>
);

function InterviewScreen(){return <div className="ui-window interview-window">
  <div className="window-bar"><span className="traffic"><i/><i/><i/></span><b>hirewise</b><span className="window-actions">⌕ &nbsp; ◌</span></div>
  <div className="interview-app">
    <aside className="side-nav"><b>hw</b><span className="nav-icon active">⌂</span><span className="nav-icon">▣</span><span className="nav-icon">◇</span><span className="nav-icon">◫</span><i>MS</i></aside>
    <div className="interview-main">
      <div className="ui-heading"><div><small>MONDAY, AUGUST 28</small><h3>Interview workspace</h3></div><button>＋ New interview</button></div>
      <div className="interview-layout">
        <section className="overview-panel"><div className="overview-top"><div><span>THIS WEEK</span><strong>24</strong><small>interviews scheduled</small></div><div className="mini-chart"><i/><i/><i/><i/><i/><i/><i/></div></div><div className="panel-title"><b>Today</b><span>5 interviews</span></div>
          <div className="timeline"><div className="time">09:30</div><div className="candidate lilac"><b>Product Designer</b><span>Amina Bello · Portfolio review</span></div><div className="faces"><i>AH</i><i>+2</i></div></div>
          <div className="timeline"><div className="time">12:00</div><div className="candidate peach"><b>Frontend Engineer</b><span>Khalid Musa · Technical</span></div><div className="faces"><i>MS</i><i>+3</i></div></div>
          <div className="timeline"><div className="time">15:30</div><div className="candidate mint"><b>Product Manager</b><span>Temi Akin · Final round</span></div><div className="faces"><i>AO</i><i>+2</i></div></div>
        </section>
        <section className="detail-panel"><div className="detail-tag">NEXT INTERVIEW</div><div className="candidate-avatar">AB</div><h4>Amina Bello</h4><p>Product Designer</p><div className="score-ring"><strong>84</strong><span>match score</span></div><dl><div><dt>TIME</dt><dd>09:30—10:15</dd></div><div><dt>PANEL</dt><dd>3 interviewers</dd></div></dl><button className="join-btn">Open interview room →</button></section>
      </div>
    </div>
  </div>
  <div className="float-toast"><span>✓</span><div><b>Interview confirmed</b><small>Everyone is in the loop.</small></div></div>
  </div>}

function MahliScreen(){return <div className="phone-stage">
  <div className="phone mahli-home"><div className="phone-notch"/><header><b>MAHLI<span>●</span></b><i>Bag · 0</i></header><small className="hello">GOOD MORNING, MARYAM</small><h3>What are you<br/><em>in the mood for?</em></h3><div className="category-row"><span className="selected">Matcha</span><span>Coffee</span><span>Brunch</span></div><div className="featured-drink"><small>MAHLI FAVOURITE</small><strong>Strawberry<br/>cream matcha</strong><span>₦5,500</span><button>＋</button></div><div className="mobile-nav"><b>⌂<small>Home</small></b><b>♡<small>Saved</small></b><b>⌕<small>Search</small></b></div></div>
  <div className="phone mahli-detail"><div className="phone-notch"/><div className="detail-hero"><header><b>←</b><i>♡</i></header><span className="cup-mark">M</span><small>STRAWBERRY / MATCHA</small></div><div className="drink-info"><div><h3>Strawberry cream matcha</h3><b>₦5,500</b></div><p>Ceremonial matcha, fresh strawberry and vanilla cream.</p><small>CHOOSE YOUR MILK</small><div className="option-row"><span className="picked">Oat</span><span>Whole</span><span>Almond</span></div><button>Add to order · ₦5,500</button></div></div>
  <div className="order-pill"><span>2</span><div><small>YOUR ORDER</small><b>Ready in 25—35 min</b></div><strong>₦10,300 →</strong></div>
  </div>}

function SiteCheckScreen(){return <div className="sitecheck-board">
  <aside className="sc-sidebar"><b>sc<span>.</span></b><div><i className="active">⌂</i><i>▣</i><i>✓</i><i>◫</i></div><em>MS</em></aside>
  <div className="sc-main">
    <header className="sc-topbar"><div><span>PORTFOLIO</span><b>Jahi Residence</b></div><div><i>⌕</i><i>◌</i><em>Maryam S.</em></div></header>
    <div className="sc-content">
      <div className="sc-heading"><div><small>INSPECTION / SC–042</small><h3>Routine inspection</h3><p>28 August 2026 · Started 9:30 AM</p></div><button>Complete inspection <span>→</span></button></div>
      <div className="sc-overview">
        <section className="sc-progress-card"><div className="sc-progress-copy"><small>OVERALL PROGRESS</small><strong>78<sup>%</sup></strong><p>14 of 18 areas checked</p></div><div className="sc-progress-track"><i/><span>4 areas remaining</span></div><div className="sc-score"><span>Property condition</span><b>Good</b></div></section>
        <section className="sc-metric"><small>OPEN ISSUES</small><strong>04</strong><p><i/> 2 need attention</p></section>
        <section className="sc-metric"><small>EVIDENCE</small><strong>12</strong><p>Photos & notes</p></section>
      </div>
      <div className="sc-dashboard-grid">
        <section className="sc-checklist"><header><div><b>Inspection checklist</b><small>AREA STATUS</small></div><span>View full checklist →</span></header><div className="sc-area-row"><i className="done">✓</i><div><b>Living spaces</b><small>4 of 4 checks complete</small></div><span className="bar"><i className="full"/></span><em>100%</em></div><div className="sc-area-row"><i className="warn">!</i><div><b>Kitchen</b><small>3 of 5 checks complete</small></div><span className="bar"><i className="part"/></span><em>60%</em></div><div className="sc-area-row"><i className="done">✓</i><div><b>Bedrooms</b><small>5 of 5 checks complete</small></div><span className="bar"><i className="full"/></span><em>100%</em></div><div className="sc-area-row"><i className="open">○</i><div><b>Exterior</b><small>2 of 4 checks complete</small></div><span className="bar"><i className="half"/></span><em>50%</em></div></section>
        <section className="sc-issue-card"><header><b>Priority issue</b><span>HIGH</span></header><div className="sc-issue-photo"><i>2 photos</i></div><small>PLUMBING · KITCHEN</small><h4>Leak beneath kitchen sink</h4><p>Active moisture around the pipe joint. Requires a plumber within 24 hours.</p><div className="sc-assignee"><i>AU</i><div><small>ASSIGNED TO</small><b>Abubakar Umar</b></div><span>Open issue →</span></div></section>
      </div>
    </div>
  </div>
  <div className="sc-toast"><i>✓</i><div><b>Living spaces complete</b><small>All four checks have passed.</small></div><span>×</span></div>
  </div>}

function NairaScreen(){return <div className="finance-stage"><div className="finance-card"><header><b>nara.</b><div><span>Overview</span><span>Transactions</span><span>Goals</span><i>MS</i></div></header><div className="finance-heading"><div><small>GOOD MORNING, MARYAM</small><h3>Your money, at a glance.</h3></div><button>＋ Add money</button></div><div className="finance-grid"><div className="balance-card"><small>TOTAL BALANCE</small><strong>₦3,648,200<sup>.00</sup></strong><span>↑ 8.4% this month</span><div className="line-chart"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="axis"><span>1 Aug</span><span>8 Aug</span><span>15 Aug</span><span>22 Aug</span></div></div><div className="spend-card"><small>SPENDING PLAN</small><strong>₦184,400</strong><span>of ₦300,000</span><div className="donut"><i/></div><p><b>₦115,600</b> left this month</p></div><div className="transactions"><div><b>Recent activity</b><span>See all →</span></div><p><i className="trans-icon">⌂</i><b>Cowrywise<small>Investment</small></b><strong>−₦50,000</strong></p><p><i className="trans-icon">✦</i><b>MAHLI<small>Food & drink</small></b><strong>−₦5,500</strong></p><p><i className="trans-icon">↙</i><b>Incoming transfer<small>Today, 09:42</small></b><strong className="income">+₦177,000</strong></p></div><div className="goal-card"><small>TOP GOAL</small><h4>First development</h4><div><i/></div><p><b>₦3.6m</b><span>of ₦10m · 36%</span></p></div></div></div><div className="insight-float"><span>✦</span><div><small>NARA INSIGHT</small><b>You saved 14% more this month</b></div><i>×</i></div></div>}

function RoamScreen(){return <div className="travel-stage"><div className="phone roam-list"><div className="phone-notch"/><header><b>roam</b><i>MS</i></header><small>NEXT TRIP</small><h3>Tokyo<br/>in October.</h3><div className="trip-meta"><span><small>DATES</small><b>12—21 Oct</b></span><span><small>TRAVELLERS</small><b>4 friends</b></span></div><div className="day-card active"><span>12</span><div><small>DAY ONE</small><b>Arrival & Shibuya</b><p>3 places · 1 booking</p></div><i>→</i></div><div className="day-card"><span>13</span><div><small>DAY TWO</small><b>Slow morning in Ginza</b><p>4 places · 2 saves</p></div><i>→</i></div><div className="mobile-nav"><b>⌂<small>Trips</small></b><b>⌕<small>Explore</small></b><b>♡<small>Saved</small></b></div></div><div className="phone roam-plan"><div className="phone-notch"/><header><b>←</b><span>Day one</span><i>•••</i></header><div className="map-panel"><span className="map-line"/><i className="pin p1">1</i><i className="pin p2">2</i><i className="pin p3">3</i><div className="weather">22° · Clear</div></div><div className="day-plan"><small>SUNDAY, 12 OCTOBER</small><h3>Arrival & Shibuya</h3><div className="plan-stop"><span>09:30</span><i>✈</i><b>Land at Haneda<small>Terminal 3</small></b></div><div className="plan-stop"><span>14:00</span><i>⌂</i><b>Check in<small>Shibuya, Tokyo</small></b></div><div className="plan-stop"><span>18:30</span><i>✦</i><b>Crossing & dinner<small>Saved by Hafsah</small></b></div></div></div><div className="collab-pill"><div><i>H</i><i>A</i><i>+2</i></div><span>Everyone voted. Day 2 is locked!</span></div></div>}

export default function Home() { return <main>
  <header className="site-header shell"><a className="wordmark" href="#top">MS<span>.</span></a><nav aria-label="Primary navigation"><a href="#work">Work</a><a href="#systems">Systems</a><a href="#about">About</a><a className="nav-cta" href="mailto:muhammadmaryam831@gmail.com">Let’s talk <Arrow /></a></nav></header>

  <section className="hero shell" id="top"><div className="eyebrow"><span className="status-dot"/> Abuja, Nigeria · Available for UI/UX roles</div><h1>I make complex products feel <em>clear, useful</em> and human.</h1><div className="hero-bottom"><p>I’m Maryam, a UI/UX designer who brings structure to messy problems and character to every interface.</p><div className="hero-links"><a href="#work">Selected work ↓</a><a href="mailto:muhammadmaryam831@gmail.com">Email me ↗</a></div></div></section>

  <section className="work shell" id="work"><div className="section-heading"><p>Selected work</p><span>Five product explorations · 2025—2026</span></div>
    <article className="project project-dark"><ProjectInfo number="01" type="Hiring platform" title="Hirewise" description="A focused interview workspace that gives recruiters, panelists and candidates one clear source of truth." tags={["UX strategy","Product design","Design system"]} link="#case-study-one"/><div className="project-visual interview-visual"><InterviewScreen/></div></article>
    <div className="case-study" id="case-study-one"><div className="case-intro"><p>THE CHALLENGE</p><h3>Make coordination feel like one flow—not five separate tasks.</h3></div><div className="case-body"><p>Scheduling an interview usually means moving between calendars, spreadsheets and message threads. I reframed the experience around one workspace with clear ownership, status and next actions.</p><dl><div><dt>Role</dt><dd>Product Designer</dd></div><div><dt>Timeline</dt><dd>3 weeks</dd></div><div><dt>Focus</dt><dd>Clarity & coordination</dd></div></dl></div><div className="process-grid"><div><span>01</span><h4>Understand</h4><p>Mapped the end-to-end scheduling journey and points of uncertainty.</p></div><div><span>02</span><h4>Prioritise</h4><p>Made schedule, ownership and candidate status immediately visible.</p></div><div><span>03</span><h4>Systemise</h4><p>Created reusable patterns for panels, interviews and success states.</p></div><div className="result"><span>DESIGN OUTCOME</span><h4>One shared picture</h4><p>Every participant can see what is happening and what they need to do next.</p></div></div></div>

    <article className="project project-cream"><ProjectInfo number="02" type="Mobile commerce" title="MAHLI" description="A warm, mobile-first ordering journey for an Abuja food brand—designed to turn craving into checkout quickly." tags={["Product thinking","Mobile UI","Visual identity"]} link="#case-study-two"/><div className="project-visual mahli-visual"><MahliScreen/></div></article>
    <div className="case-study" id="case-study-two"><div className="case-intro"><p>THE OPPORTUNITY</p><h3>Let the brand feel playful without making ordering feel busy.</h3></div><div className="case-body"><p>I designed a menu that leads with appetite, keeps choices light and makes customisation feel effortless. The visual system uses warm cream, grounded green and expressive editorial type.</p><dl><div><dt>Role</dt><dd>Product & UI Designer</dd></div><div><dt>Platform</dt><dd>Mobile web</dd></div><div><dt>Focus</dt><dd>Conversion & brand</dd></div></dl></div><div className="feature-row"><div><small>01 / DISCOVER</small><h4>Clear categories reduce browsing effort.</h4></div><div><small>02 / CUSTOMISE</small><h4>Options appear only when they matter.</h4></div><div><small>03 / CHECKOUT</small><h4>A persistent order bar keeps progress visible.</h4></div></div></div>

    <article className="project project-blue"><ProjectInfo number="03" type="Property technology" title="SiteCheck" description="A field inspection workspace for capturing issues, evidence and follow-ups without paper forms." tags={["UX research","Responsive UI","Prototyping"]}/><div className="project-visual sitecheck-visual"><SiteCheckScreen/></div></article>
    <article className="project project-violet"><ProjectInfo number="04" type="Fintech dashboard" title="Nara" description="A personal finance command centre that turns balances, spending and goals into decisions people can act on." tags={["Data visualisation","Dashboard UI","Product strategy"]}/><div className="project-visual finance-visual"><NairaScreen/></div></article>
    <article className="project project-coral"><ProjectInfo number="05" type="Travel planning" title="Roam" description="A collaborative trip planner that helps friends turn scattered saves and group-chat ideas into one workable itinerary." tags={["Mobile UX","Collaboration","Interaction design"]}/><div className="project-visual roam-visual"><RoamScreen/></div></article>
  </section>

  <section className="systems shell" id="systems"><div className="section-heading"><p>Design systems</p><span>Colour, type and repeatable decisions</span></div><div className="systems-intro"><h2>Good interfaces need a visual point of view—and rules that hold it together.</h2><p>I use colour to communicate hierarchy and status, then build typography around legibility, rhythm and the character of the product.</p></div><div className="system-grid"><article className="colour-system"><div className="system-title"><small>01 / COLOUR SYSTEM</small><h3>Purpose before decoration.</h3></div><div className="swatches"><div className="swatch forest"><span>#245B3D</span><b>Primary action</b></div><div className="swatch sage"><span>#C9D8C6</span><b>Support surface</b></div><div className="swatch ink"><span>#111411</span><b>High contrast</b></div><div className="swatch paper"><span>#FBFCF9</span><b>Breathing room</b></div></div><p>One strong accent carries interactive moments; neutrals do the quiet structural work.</p></article><article className="type-system"><div className="system-title"><small>02 / TYPOGRAPHY</small><h3>Hierarchy you can feel.</h3></div><div className="type-specimen"><span className="type-sans">Aa</span><div><small>INTER / INTERFACE</small><b>Clear at every size</b></div></div><div className="type-specimen serif"><span>Aa</span><div><small>EDITORIAL SERIF / EXPRESSION</small><b>Warmth and character</b></div></div><div className="type-scale"><span>Display · 72/68</span><span>Heading · 32/36</span><span>Body · 16/26</span><span>Label · 11/14</span></div></article></div></section>

  <section className="about shell" id="about"><div className="section-heading"><p>About</p><span>Products with presence</span></div><div className="about-grid"><h2>I shape the product and the world around it.</h2><div><p>I’m a UI/UX designer and brand builder based in Abuja. I work where product thinking meets visual identity—designing useful digital experiences and giving brands a clear, memorable point of view.</p><p>I enjoy taking messy information, finding the useful thread and turning it into something people can understand, trust and enjoy using.</p><div className="skills"><span>Interface design</span><span>Brand building</span><span>User flows</span><span>Visual identity</span><span>Prototyping</span><span>Design systems</span><span>Figma</span></div></div></div></section>

  <footer id="contact"><div className="shell contact-inner"><p>Have a product that needs clarity?</p><h2>Let’s make it easier to use.</h2><div className="contact-list"><a href="mailto:muhammadmaryam831@gmail.com"><small>EMAIL</small><span>muhammadmaryam831@gmail.com</span><Arrow/></a><a href="tel:+2349020280654"><small>PHONE</small><span>090 2028 0654</span><Arrow/></a><a href="https://www.linkedin.com/in/maryam-shehu-muhammad-88789427b" target="_blank" rel="noreferrer"><small>LINKEDIN</small><span>Maryam Shehu Muhammad</span><Arrow/></a></div><div className="footer-row"><span>© 2026 Maryam Shehu</span><span>UI/UX Designer · Abuja, Nigeria</span><a href="#top">Back to top ↑</a></div></div></footer>
  </main> }
