import type {Project} from "./project-data";
import {LandingPreview} from "./full-landings";
import {GonaDistinct,NadiDistinct,ToldDistinct} from "./distinct-screens";

const Face=({children}:{children:string})=><i className="face">{children}</i>;

function Hirewise({kind}:{kind:string}){
 if(kind==="hire-landing")return <div className="ui-canvas hw-ui hw-landing"><header><b>hirewise</b><nav>Product&nbsp;&nbsp;&nbsp; For teams&nbsp;&nbsp;&nbsp; Candidate care</nav><button>Book a walkthrough ↗</button></header><main><section><small>INTERVIEWS, HELD TOGETHER</small><h2>Good hiring<br/>needs a <em>room.</em></h2><p>Schedule the people. Prepare the panel. Run the conversation. Keep the evidence together.</p><div><button>See the workspace →</button><span>Built for teams hiring<br/>without a full ops department.</span></div></section><aside><div className="hw-land-grid"><article><small>NEXT INTERVIEW</small><b>10:30</b><span>Amina Bello · Portfolio</span></article><article className="mint"><small>PANEL READY</small><b>3 / 3</b><span>Briefs opened</span></article><article className="wide"><small>THE HANDOFF</small><p>Schedule → prepare → interview → decide</p><i>Evidence stays sealed until everyone submits.</i></article></div></aside></main></div>;
 if(kind==="hire-schedule")return <div className="ui-canvas hw-ui hw-schedule">
  <aside><b className="hw-logo">h/w</b><small>NEW INTERVIEW</small><ol><li className="done">01 Candidate</li><li className="active">02 Schedule</li><li>03 Panel</li><li>04 Brief</li></ol><span>Autosaved 11:42</span></aside>
  <main><header><b>Amina Bello</b><span>Product Designer · Portfolio interview</span><button>Save & exit</button></header><div className="hw-schedule-head"><div><small>STEP 02</small><h3>Let’s find a time<br/>without another email.</h3></div><p>Four calendars are connected.<br/>Times shown in WAT.</p></div><div className="hw-week"><span/><b>MON 28</b><b className="today">TUE 29</b><b>WED 30</b><b>THU 31</b><span>09:00</span><i>2/4 free</i><i>Conflict</i><i>3/4 free</i><i>4/4 free</i><span>10:30</span><i>3/4 free</i><i className="best">BEST MATCH<br/><strong>4/4 available</strong></i><i>2/4 free</i><i>3/4 free</i><span>13:00</span><i>Conflict</i><i>3/4 free</i><i>4/4 free</i><i>2/4 free</i></div><footer><span>Selected: Tue 29 August · 10:30—11:15</span><button>Continue to panel →</button></footer></main>
 </div>;
 if(kind==="hire-room")return <div className="ui-canvas hw-ui hw-room"><header><b className="hw-logo">hirewise</b><span className="live">● LIVE · 24:16</span><span>Product Designer / Amina Bello</span><button>Leave room</button></header><main><section className="hw-video"><div className="speaker"><span>AB</span><small>Amina Bello</small></div><div className="panel-video"><span>MS</span><small>You · Facilitator</small></div><div className="panel-video"><span>AO</span><small>Aliyu · Panelist</small></div><div className="panel-video muted"><span>HK</span><small>Hauwa · Muted</small></div></section><aside><div className="hw-question"><small>QUESTION 03 / 06 · YOURS</small><h3>Tell us about a decision you changed after user feedback.</h3><button>Show follow-up prompt</button></div><label>PRIVATE EVIDENCE</label><textarea readOnly value="Amina explained why the first navigation model failed during testing…"/><div className="hw-score"><span>Evidence score</span>{[1,2,3,4,5].map(n=><b className={n===4?"on":""} key={n}>{n}</b>)}</div><footer><span>Notes stay sealed until submission.</span><button>Save & next →</button></footer></aside></main></div>;
 if(kind==="hire-candidate")return <div className="ui-canvas hw-ui hw-candidate"><header><b className="hw-logo">hirewise</b><span>Candidate space</span><button>Need help?</button></header><main><section><small>INTERVIEW CONFIRMED</small><h2>Hi Amina.<br/>Here’s exactly<br/>what to expect.</h2><p>Product Designer · Tuesday, 29 August</p><div className="hw-people"><Face>MS</Face><Face>AO</Face><Face>HK</Face><span>Maryam, Aliyu and Hauwa<br/>will be speaking with you.</span></div></section><aside><article><small>WHEN</small><strong>10:30—11:15</strong><span>West Africa Time</span><button>Add to calendar ↗</button></article><article><small>FORMAT</small><strong>Video interview</strong><span>45 minutes · 3 people</span><button>Test your setup ↗</button></article><article className="wide"><small>WHAT WE’LL TALK ABOUT</small><h3>Your process, one project you’re proud of, and how you make decisions with a team.</h3><button>Read the interview guide →</button></article><button className="enter">Enter waiting room →</button></aside></main></div>;
 return <div className="ui-canvas hw-ui hw-home"><aside><b className="hw-logo">h/w</b><nav><i className="on">01</i><i>02</i><i>03</i><i>04</i></nav><Face>MS</Face></aside><main><header><div><small>MONDAY / 28 AUGUST</small><h3>Good morning, Maryam.</h3></div><button>＋ Create interview</button></header><div className="hw-snapshot"><article><small>THIS WEEK</small><strong>24</strong><span>interviews</span><div className="hw-bars"><i/><i/><i/><i/><i/></div></article><article><small>NEEDS ATTENTION</small><strong>06</strong><span>2 feedback forms overdue</span></article><article className="next"><small>UP NEXT · 28 MIN</small><div><Face>AB</Face><b>Amina Bello<em>Product Designer</em></b></div><button>Open interview room →</button></article></div><div className="hw-day"><div className="hw-day-title"><h4>Today</h4><span>5 interviews · WAT</span><button>Full calendar ↗</button></div>{[["09:30","AB","Amina Bello","Portfolio","Ready"],["12:00","KM","Khalid Musa","Technical","Brief missing"],["15:30","TA","Temi Akin","Final","Ready"]].map((x,i)=><article key={x[0]}><time>{x[0]}</time><Face>{x[1]}</Face><b>{x[2]}<small>Product {i===1?"Engineer":i===2?"Manager":"Designer"}</small></b><span>{x[3]}</span><em className={i===1?"warn":""}>● {x[4]}</em><i>→</i></article>)}</div></main></div>
}

function Mahli({kind}:{kind:string}){
 if(kind==="mahli-product")return <div className="ui-canvas mh-ui mh-product"><header><b>MAHLI<span>●</span></b><nav>Menu &nbsp;&nbsp; Our story &nbsp;&nbsp; Find us</nav><button>Bag · 2</button></header><main><section className="mh-product-art"><small>STRAWBERRY / MATCHA</small><strong>M</strong><p>whisked<br/>to order</p></section><section className="mh-product-info"><small>MAHLI FAVOURITE</small><h2>Strawberry<br/>cream matcha</h2><p>Ceremonial matcha, fresh strawberry and a soft vanilla cream.</p><div className="mh-price"><b>₦5,500</b><span>12 oz · iced</span></div><label>CHOOSE YOUR MILK</label><div className="mh-options"><button className="on">Oat</button><button>Whole</button><button>Almond +₦500</button></div><label>SWEETNESS</label><div className="mh-sweet"><span>0%</span><i/><b>50%</b><i/><span>100%</span></div><button className="mh-add">Add to bag · ₦5,500</button></section></main></div>;
 if(kind==="mahli-checkout")return <div className="ui-canvas mh-ui mh-checkout"><header><b>MAHLI<span>●</span></b><span>CHECKOUT / 02</span><button>← Keep shopping</button></header><main><section><small>YOUR ORDER</small><h2>Almost yours.</h2><div className="mh-order"><i className="pink">M</i><b>Strawberry cream matcha<small>Oat · 50% sweet · 12 oz</small></b><span>1</span><strong>₦5,500</strong></div><div className="mh-order"><i className="gold">M</i><b>Belgian waffle<small>Maple · berries</small></b><span>1</span><strong>₦4,800</strong></div><button>＋ Add something else</button></section><aside><small>DELIVERY</small><div className="mh-tabs"><b className="on">Delivery</b><b>Pickup</b></div><article><span>TO</span><b>Home · Wuse 2</b><button>Change</button></article><article><span>WHEN</span><b>As soon as possible</b><em>25—35 min</em></article><dl><div><dt>Items</dt><dd>₦10,300</dd></div><div><dt>Delivery</dt><dd>₦1,500</dd></div><div><dt>Total</dt><dd>₦11,800</dd></div></dl><button className="mh-pay">Pay ₦11,800 →</button></aside></main></div>;
 if(kind==="mahli-track")return <div className="ui-canvas mh-ui mh-track"><header><b>MAHLI<span>●</span></b><span>ORDER MH–184</span><button>Need help?</button></header><main><section><small>ESTIMATED DELIVERY</small><div className="mh-count"><strong>24</strong><span>MINUTES</span></div><h2>Your good mood<br/>is being made.</h2></section><aside><div className="mh-progress"><article className="done"><i>✓</i><b>Order confirmed<small>4:08 PM</small></b></article><article className="current"><i>02</i><b>Being prepared<small>Your matcha is being whisked now</small></b></article><article><i>03</i><b>Out for delivery<small>Next update</small></b></article><article><i>04</i><b>At your door<small>Enjoy it immediately</small></b></article></div><footer><Face>IB</Face><b>Ibrahim<small>Your delivery partner</small></b><button>Call</button><button>Message</button></footer></aside></main></div>;
 return <div className="ui-canvas mh-ui mh-home"><header><b>MAHLI<span>●</span></b><nav>Matcha &nbsp;&nbsp; Coffee &nbsp;&nbsp; Brunch</nav><button>Bag · 2</button></header><main><div className="mh-hello"><small>GOOD AFTERNOON, MARYAM</small><h2>Pick a mood.<br/><em>We’ll make the rest.</em></h2><div><button className="on">Matcha</button><button>Coffee</button><button>Brunch</button></div></div><div className="mh-feature"><small>THE ONE EVERYONE REORDERS</small><h3>Strawberry<br/>cream matcha</h3><span>₦5,500</span><b>M</b><button>Make it mine ＋</button></div><aside><article><i className="coffee">M</i><small>COFFEE</small><b>Iced Spanish latte</b><span>₦4,800</span></article><article><i className="waffle">M</i><small>BRUNCH</small><b>Pistachio waffle</b><span>₦5,200</span></article></aside></main></div>
}

function SiteCheck({kind}:{kind:string}){
 if(kind==="site-landing")return <div className="ui-canvas sc-ui sc-landing"><header><b>SiteCheck.</b><nav>FIELD TOOL / REPORTS / REPAIR LOG</nav><button>REQUEST DEMO ↗</button></header><main><section><span>01</span><small>PROPERTY CONDITION, WITHOUT THE GUESSWORK</small><h2>Capture it<br/>where it<br/><em>happens.</em></h2><p>Inspection evidence, condition reports and verified repair history in one field-to-office record.</p><button>SEE THE WORKFLOW →</button></section><aside><div className="sc-land-plan"><small>INSPECTION / SC–042</small><b>JAHI<br/>RESIDENCE</b><div><i/><i/><i/><i/></div><span>18 AREAS · 4 ISSUES · 12 EVIDENCE FILES</span></div><footer><b>FIELD FIRST</b><span>Works area by area<br/>and photo by photo.</span><strong>78%</strong></footer></aside></main></div>;
 if(kind==="site-capture")return <div className="ui-canvas sc-ui sc-capture"><aside><b>SC/042</b><span>JAHI RESIDENCE</span><strong>03</strong><small>OF 06 AREAS</small><div className="sc-vertical"><i/></div><button>Exit inspection</button></aside><main><header><div><small>AREA 03</small><h2>Kitchen</h2></div><span>28 AUG 2026 / 10:31</span><button>•••</button></header><div className="sc-checks">{[["Walls & ceiling","PASS","No visible defects"],["Cabinets & surfaces","PASS","Minor wear only"],["Plumbing","ISSUE","Leak below sink"],["Electrical","OPEN","Not checked"]].map((x,i)=><article className={`r${i}`} key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><b>{x[0]}<small>{x[2]}</small></b><em>{x[1]}</em><button>{i===2?"2 PHOTOS":i===3?"CHECK":"✓"}</button></article>)}</div><footer><button className="evidence">＋ ADD PHOTO OR NOTE</button><button className="continue">SAVE / NEXT AREA →</button></footer></main></div>;
 if(kind==="site-issue")return <div className="ui-canvas sc-ui sc-issue"><header><b>SITECHECK / ISSUE REGISTER</b><span>SC–042–04</span><button>×</button></header><main><section><div className="sc-evidence"><span>EVIDENCE 01 / 02</span><strong>PLUMBING</strong></div><div className="sc-thumbs"><i>01</i><i>02</i><button>＋</button></div></section><aside><div className="sc-priority"><span>HIGH PRIORITY</span><b>RESPOND WITHIN 24H</b></div><small>KITCHEN / PLUMBING</small><h2>Leak beneath<br/>kitchen sink</h2><p>Active moisture around the pipe joint. The lower cabinet is beginning to swell.</p><dl><div><dt>REPORTED BY</dt><dd>Maryam S. · 10:42</dd></div><div><dt>ASSIGNED TO</dt><dd>Abubakar Umar</dd></div><div><dt>DUE</dt><dd>Tomorrow · 10:42</dd></div></dl><div className="sc-status"><i className="done">✓</i><span/><i className="active">02</i><span/><i>03</i><b>RECORDED</b><b>REPAIR</b><b>VERIFY</b></div><button>MESSAGE ASSIGNEE →</button></aside></main></div>;
 if(kind==="site-report")return <div className="ui-canvas sc-ui sc-report"><aside><b>SiteCheck.</b><span>PROPERTY CONDITION REPORT</span><strong>SC<br/>042</strong><small>28 / 08 / 2026</small></aside><main><header><small>JAHI RESIDENCE</small><span>PREPARED FOR MS PROPERTY</span></header><h2>Routine inspection<br/>summary</h2><div className="sc-grade"><strong>GOOD</strong><span>OVERALL CONDITION</span></div><div className="sc-report-stats"><article><b>18</b><span>AREAS CHECKED</span></article><article><b>04</b><span>ISSUES FOUND</span></article><article><b>02</b><span>ACTIONS REQUIRED</span></article></div><section><small>PRIORITY FINDING / 01</small><h3>Kitchen plumbing needs attention within 24 hours.</h3><button>VIEW EVIDENCE ↗</button></section><div className="sc-condition"><p><span>INTERIOR</span><i><b style={{width:"88%"}}/></i><strong>GOOD</strong></p><p><span>SERVICES</span><i><b style={{width:"62%"}}/></i><strong>FAIR</strong></p><p><span>EXTERIOR</span><i><b style={{width:"92%"}}/></i><strong>GOOD</strong></p></div></main></div>;
 return <div className="ui-canvas sc-ui sc-home"><header><b>SiteCheck.</b><nav>PORTFOLIO / INSPECTIONS / ISSUES / REPORTS</nav><span>MS</span></header><main><aside><small>ACTIVE INSPECTION</small><strong>SC<br/>042</strong><span>JAHI RESIDENCE</span><div><i style={{height:"78%"}}/></div><b>78%</b><p>14 OF 18 AREAS</p><button>RESUME ON MOBILE ↗</button></aside><section><div className="sc-title"><div><small>28 AUGUST 2026 / 09:30</small><h2>Routine inspection</h2></div><button>COMPLETE INSPECTION →</button></div><div className="sc-metrics"><article><span>OPEN ISSUES</span><b>04</b><small>2 NEED ATTENTION</small></article><article><span>EVIDENCE</span><b>12</b><small>PHOTOS + NOTES</small></article><article><span>CONDITION</span><b>GOOD</b><small>PROVISIONAL</small></article></div><div className="sc-area-list"><header><b>AREA REGISTER</b><span>STATUS / CHECKS / EVIDENCE</span></header>{[["01","Living spaces","COMPLETE","04 / 04","3"],["02","Bedrooms","COMPLETE","05 / 05","4"],["03","Kitchen","ISSUE","03 / 05","2"],["04","Exterior","OPEN","02 / 04","3"]].map((x,i)=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em className={`s${i}`}>{x[2]}</em><i>{x[3]}</i><strong>{x[4]}</strong><button>→</button></article>)}</div></section></main></div>
}

function Nara({kind}:{kind:string}){
 if(kind==="nara-landing")return <div className="ui-canvas nr-ui nr-landing"><header><b>nara°</b><nav>How it works&nbsp;&nbsp;&nbsp; Security&nbsp;&nbsp;&nbsp; Notes</nav><button>Join the private beta</button></header><main><section><small>ONE READ-ONLY VIEW</small><h2>Money feels<br/>different when<br/><em>you can see it.</em></h2><p>Bring savings, investments and everyday balances into one honest position—without moving your money.</p><button>See your full position →</button></section><aside><div className="nr-land-number"><small>COMPLETE POSITION</small><b>₦3.64m</b><span>across 4 linked accounts</span></div><div className="nr-land-note"><i>✦</i><p>You added more to your future than you spent on your present this month.</p><span>See the working →</span></div></aside></main></div>;
 if(kind==="nara-flow")return <div className="ui-canvas nr-ui nr-flow"><header><b>nara°</b><span>AUGUST / CASH FLOW</span><button>Export</button></header><main><section><small>THE SHORT VERSION</small><h2>You kept more<br/>this month.</h2><p>Your income rose. Day-to-day spending barely moved.</p><div className="nr-rate"><strong>40%</strong><span>SAVED<br/>OF INCOME</span></div></section><aside><div className="nr-flow-head"><article><small>MONEY IN</small><b>₦627,000</b><span>+6% vs July</span></article><article><small>TRUE SPEND</small><b>₦284,600</b><span>−₦18,400</span></article></div><div className="nr-waterfall"><i style={{height:"82%"}}/><i style={{height:"42%"}}/><i style={{height:"35%"}}/><i style={{height:"18%"}}/><i style={{height:"52%"}}/></div><div className="nr-cats">{[["Family & giving","₦100k","35%"],["Transport","₦74.2k","26%"],["Food & life","₦58.4k","21%"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></p>)}</div><footer>Transfers between your own accounts have been removed. <button>See how ↗</button></footer></aside></main></div>;
 if(kind==="nara-goal")return <div className="ui-canvas nr-ui nr-goal"><header><b>nara°</b><span>GOAL LAB / FIRST DEVELOPMENT</span><button>Close</button></header><main><section><small>FUNDED SO FAR</small><strong>₦3,648,200</strong><div className="nr-goal-line"><i/><span>36%</span></div><h2>At this pace,<br/>October 2028.</h2></section><aside><small>TRY A DIFFERENT MONTHLY AMOUNT</small><div className="nr-input"><span>₦</span><strong>300,000</strong><em>/ month</em></div><div className="nr-slider"><i/><b/></div><div className="nr-impact"><span>NEW DATE</span><strong>May 2028</strong><em>5 months sooner</em></div><p>This assumes your existing ₦3.64m stays invested and you contribute every month.</p><button>USE THIS PLAN →</button></aside></main></div>;
 if(kind==="nara-insight")return <div className="ui-canvas nr-ui nr-insight"><header><b>nara°</b><span>INSIGHT / AUGUST</span><button>×</button></header><main><span className="nr-star">✦</span><small>WE NOTICED SOMETHING</small><h2>Your savings rate improved.<br/>Your flexible spending didn’t.</h2><p>You saved more because your income rose—not because your everyday spending changed much.</p><div className="nr-proof"><article><span>SAVINGS RATE</span><b>40%</b><em>+9 pts</em></article><article><span>FLEXIBLE SPEND</span><b>₦132.6k</b><em>−1.2%</em></article><article><span>CONFIDENCE</span><b>HIGH</b><em>12 records</em></article></div><footer><button>THIS LOOKS WRONG</button><button className="primary">PLAN SEPTEMBER →</button></footer></main></div>;
 return <div className="ui-canvas nr-ui nr-home"><header><b>nara°</b><nav>POSITION &nbsp; CASH FLOW &nbsp; GOALS</nav><button>＋ Link account</button></header><main><div className="nr-intro"><small>FRIDAY / 28 AUGUST</small><h2>₦3,648,200</h2><p>Your complete position</p><span>↑ 8.4% this month</span></div><div className="nr-chart"><div className="nr-chart-line"><i/><i/><i/><i/><i/><i/><i/></div><footer><span>01 AUG</span><span>08</span><span>15</span><span>22</span><span>TODAY</span></footer></div><div className="nr-bottom"><article><small>AVAILABLE</small><strong>₦438k</strong><span>12%</span></article><article><small>INVESTED</small><strong>₦3.21m</strong><span>88%</span></article><article className="nr-note"><small>NARA NOTE</small><h3>You saved 14% more this month.</h3><button>See why →</button></article></div></main></div>
}

function Roam({kind}:{kind:string}){
 if(kind==="roam-save")return <div className="ui-canvas rm-ui rm-save"><header><b>ROAM / TOKYO</b><span>IDEA BOARD · 18 SAVED</span><button>＋ ADD A PLACE</button></header><main><section className="rm-feature"><div className="rm-photo"><span>FOOD / SHIBUYA</span></div><small>SAVED BY HAFSAH · ¥¥ · OPEN UNTIL 22:00</small><h2>Uobei Shibuya<br/>Dogenzaka</h2><p>Eight minutes from the hotel. Four people are interested.</p><button>PROPOSE A DAY →</button></section><aside><article><div className="rm-mini-photo art"/><span>ART / AZABUDAI</span><h3>teamLab Borderless</h3><p>Tickets needed · 3 interested</p></article><article><div className="rm-mini-photo coffee"/><span>COFFEE / OMOTESANDO</span><h3>Koffee Mameya</h3><p>Walk-in · 4 interested</p></article></aside></main></div>;
 if(kind==="roam-vote")return <div className="ui-canvas rm-ui rm-vote"><header><b>ROAM / DECISION 03</b><span>CLOSES AT 20:00 WAT</span><button>×</button></header><main><section><small>DAY TWO / MORNING</small><h2>Where should<br/>Tuesday begin?</h2><p>Four of six people have voted.</p><div className="rm-faces"><Face>MS</Face><Face>H</Face><Face>A</Face><Face>+1</Face></div></section><aside><button className="selected"><span>A</span><b>Slow morning in Ginza<small>Breakfast · shopping · 3 saves</small></b><em>✓</em></button><button><span>B</span><b>Old Tokyo in Asakusa<small>Temple · market · 4 saves</small></b><em>○</em></button><footer><span>Your choice stays private until voting closes.</span><button>SUBMIT VOTE →</button></footer></aside></main></div>;
 if(kind==="roam-plan")return <div className="ui-canvas rm-ui rm-plan"><aside><b>12</b><span>OCT<br/>SUN</span><small>DAY 01 / TOKYO</small><h2>Arrival &<br/>Shibuya</h2><p>22° · Clear · 3 places</p><div className="rm-route-list">{[["09:30","Land at Haneda","Hafsah owns this"],["14:00","Check in","Confirmed"],["18:30","Crossing + dinner","No booking"]].map(x=><article key={x[0]}><time>{x[0]}</time><b>{x[1]}<small>{x[2]}</small></b></article>)}</div></aside><main><div className="rm-map-grid"><span className="road one"/><span className="road two"/><span className="road three"/><i className="p1">1</i><i className="p2">2</i><i className="p3">3</i><small>SHIBUYA</small><em>HANEDA</em></div><div className="rm-map-note">Leave the hotel by 17:50<br/>to make dinner on time.</div></main></div>;
 return <div className="ui-canvas rm-ui rm-home"><header><b>roam</b><span>OUR TOKYO / 12—21 OCTOBER</span><div><Face>MS</Face><Face>H</Face><Face>A</Face><Face>+1</Face></div></header><main><section><small>NEXT TRIP · 44 DAYS</small><h2>Tokyo<br/><em>in October.</em></h2><div className="rm-facts"><span>9 NIGHTS</span><span>4 FRIENDS</span><span>¥180K EACH</span></div><button>3 DECISIONS NEED YOU →</button></section><aside><div className="rm-cover-photo"><span>35.6762° N<br/>139.6503° E</span></div><div className="rm-days"><article><time>12</time><b>Arrival & Shibuya<small>3 places · 1 booking</small></b><span>→</span></article><article><time>13</time><b>Slow morning in Ginza<small>4 places · voting open</small></b><span>→</span></article></div></aside></main></div>
}

function Gona({kind}:{kind:string}){
 if(kind==="gona-landing")return <div className="ui-canvas go-ui go-landing"><header><b>GONA<span>/SEASON 26</span></b><nav>HOW IT WORKS&nbsp;&nbsp; COOPERATIVES&nbsp;&nbsp; BUYERS</nav><button>START A SEASON ↗</button></header><main><section><small>FROM FIELD NOTE TO BUYER LOT</small><h2>Grow with<br/>the full<br/><em>picture.</em></h2><p>One operating system for the people planning the season, visiting the field and moving the harvest.</p><div><button>SEE GONA IN THE FIELD →</button><span>OFFLINE-FIRST<br/>BUILT FOR SHARED WORK</span></div></section><aside><div className="go-land-map"><i className="f1">F08</i><i className="f2">F12</i><i className="f3">F17</i><span>3 ACTIONS<br/>NEED A VISIT</span></div><footer><article><b>41</b><span>ACTIVE FIELDS</span></article><article><b>06</b><span>HARVEST LOTS</span></article><strong>MAIZE / WET SEASON</strong></footer></aside></main></div>;
 if(kind==="gona-field")return <div className="ui-canvas go-ui go-field"><aside><b>GONA</b><span>OFFLINE FIELD MODE</span><strong>08</strong><small>FIELD / KURMIN</small><div className="go-sync"><i/>Stored on this device</div></aside><main><header><div><small>VISIT 04 · 28 AUG</small><h2>Maize / week 11</h2></div><span>12:42 · NO SIGNAL</span></header><section><div className="go-field-photo"><span>ADD FIELD PHOTO ＋</span></div><div className="go-field-checks"><small>WHAT NEEDS RECORDING?</small>{[["01","Crop stand","EVEN"],["02","Weed pressure","MODERATE"],["03","Water stress","NOT SEEN"]].map(x=><button key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]} ↗</em></button>)}</div></section><footer><span>2 NOTES · 1 PHOTO SAVED LOCALLY</span><button>FINISH VISIT →</button></footer></main></div>;
 if(kind==="gona-lot")return <div className="ui-canvas go-ui go-lot"><header><b>GONA / HARVEST LOT</b><span>LOT GM–06–2408</span><button>SHARE WITH BUYER ↗</button></header><main><section><small>BUYER-READY OFFER</small><h2>Yellow maize<br/>Grade A</h2><div className="go-bags"><strong>186</strong><span>BAGS<br/>9,300 KG</span></div><p>Collection from Gidan Waya point.<br/>Ready from 31 August.</p></section><aside><div className="go-lot-checks"><article><small>MOISTURE CHECK</small><b>13.2%</b><span>Recorded 08:20</span></article><article><small>CONTRIBUTING FARMS</small><b>12</b><span>All records complete</span></article><article><small>COLLECTION WINDOW</small><b>06:00—11:00</b><span>31 Aug / 01 Sep</span></article></div><div className="go-lot-fields"><small>LOT COMPOSITION</small>{[["F08","18 bags"],["F12","24 bags"],["F17","16 bags"],["+9","128 bags"]].map(x=><i key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></i>)}</div><footer><span>QUALITY RECORD SIGNED BY<br/><b>Aisha Mohammed · Field lead</b></span><strong>READY</strong></footer></aside></main></div>;
 if(kind==="gona-dispatch")return <div className="ui-canvas go-ui go-dispatch"><header><b>GONA</b><span>DISPATCH / THURSDAY 31 AUGUST</span><button>PRINT YARD LIST</button></header><main><aside><small>LOAD 02 / GM–06–2408</small><h2>Buyer truck<br/>is on site.</h2><div className="go-truck"><span>KN 43 A08</span><b>118 / 186</b><em>BAGS LOADED</em></div><p>Driver: Musa Garba<br/>Destination: Zaria grain depot</p></aside><section><header><span>LOAD SEQUENCE</span><b>63% COMPLETE</b></header>{[["01","Field 08","18","DONE"],["02","Field 12","24","DONE"],["03","Field 17","16","LOADING"],["04","North cluster","42","WAITING"]].map((x,i)=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><strong>{x[2]} BAGS</strong><em className={`d${i}`}>{x[3]}</em></article>)}<footer><span>LAST COUNT SAVED 10:18 · OFFLINE</span><button>RECORD COLLECTION PROOF →</button></footer></section></main></div>;
 return <div className="ui-canvas go-ui go-desk"><header><b>GONA<span>WET SEASON / MAIZE</span></b><nav>FIELDS&nbsp;&nbsp; WORK&nbsp;&nbsp; EQUIPMENT&nbsp;&nbsp; LOTS</nav><i>MS</i></header><main><aside><small>COOPERATIVE PICTURE</small><h2>41 fields.<br/>6 need action.</h2><div className="go-map"><i className="a">08</i><i className="b">12</i><i className="c">17</i><i className="d">22</i><span>● VISIT DUE&nbsp;&nbsp; ● READY&nbsp;&nbsp; ● WATCH</span></div></aside><section><div className="go-action"><header><b>NEXT 72 HOURS</b><span>OWNER / DUE</span></header>{[["FIELD 08","Check crop stand","Aisha","TODAY"],["FIELD 17","Confirm tractor slot","Bello","29 AUG"],["LOT 06","Complete grade record","Maryam","30 AUG"]].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span><em>{x[3]}</em></article>)}</div><div className="go-machine"><small>SHARED EQUIPMENT / WEEK 35</small><div className="go-machine-grid"><b>TRACTOR 01</b><i/><i className="busy">F12</i><i className="busy">F17</i><i/><b>SHELLER</b><i className="busy">LOT 04</i><i/><i/><i className="busy">LOT 06</i></div></div></section></main></div>;
}

function Nadi({kind}:{kind:string}){
 if(kind==="nadi-landing")return <div className="ui-canvas nd-ui nd-landing"><header><b>nadi<span>care passport</span></b><nav>Families&nbsp;&nbsp; Schools&nbsp;&nbsp; Care teams&nbsp;&nbsp; Privacy</nav><button>Request early access</button></header><main><section><small>CARE INFORMATION THAT ARRIVES WITH THE CHILD</small><h2>One story.<br/><em>Fewer retellings.</em></h2><p>Nadi gives families a current care passport and shares only the part a school or clinic needs.</p><div><button>See how access works →</button><span>Non-diagnostic<br/>Family-controlled</span></div></section><aside><div className="nd-pass-card"><header><b>ZAINAB A.</b><span>CARE PASSPORT / CURRENT</span></header><div><small>PRIMARY CLINIC</small><b>Paediatric Haematology Unit</b><span>Last reviewed 24 August</span></div><footer><strong>PASS 02</strong><span>SCHOOL ACCESS<br/>EXPIRES IN 12 DAYS</span><i>↗</i></footer></div><p>Designed for the handoff between home, school and clinic.</p></aside></main></div>;
 if(kind==="nadi-school")return <div className="ui-canvas nd-ui nd-school"><aside><b>nadi</b><small>NEW SCHOOL PASS</small><ol><li className="done">01 School</li><li className="active">02 Information</li><li>03 Expiry</li><li>04 Review</li></ol><span>Family controls this pass</span></aside><main><header><span>Zainab’s care passport</span><button>Save and close</button></header><section><small>CHOOSE WHAT THE SCHOOL CAN SEE</small><h2>A useful window.<br/>Not the whole record.</h2>{[["Care contacts","Parent and clinic numbers",true],["Everyday guidance","Approved school care note",true],["Visit timeline","Dates and clinical notes",false],["Uploaded documents","Letters and lab documents",false]].map(x=><label key={String(x[0])}><i className={x[2]?"on":""}>{x[2]?"✓":""}</i><b>{x[0]}<span>{x[1]}</span></b><em>{x[2]?"SHARED":"PRIVATE"}</em></label>)}<footer><span>Pass expires: 10 September 2026</span><button>Review school pass →</button></footer></section></main></div>;
 if(kind==="nadi-visit")return <div className="ui-canvas nd-ui nd-visit"><header><b>nadi</b><span>VISIT PREPARATION / 03 SEPTEMBER</span><button>Save for later</button></header><main><section><small>BEFORE THE APPOINTMENT</small><h2>Bring the week<br/>into the room.</h2><p>This is a record for the care team, not a diagnosis.</p><div className="nd-week">{["M","T","W","T","F","S","S"].map((x,i)=><i className={i===2||i===5?"marked":""} key={`${x}${i}`}>{x}<span>{i===2||i===5?"●":""}</span></i>)}</div></section><aside><div><small>RECENT EVENTS TO REVIEW</small><article><span>26 AUG · ADDED BY PARENT</span><b>School called about tiredness after sports.</b><button>Include in visit ✓</button></article><article><span>29 AUG · DOCUMENT</span><b>Clinic letter uploaded.</b><button>Include in visit ✓</button></article></div><div className="nd-question"><small>QUESTION FOR THE CARE TEAM</small><p>What should the school know before sports day next month?</p><button>＋ Add another question</button></div><footer><span>2 events · 1 question prepared</span><button>Share with clinic →</button></footer></aside></main></div>;
 if(kind==="nadi-clinical")return <div className="ui-canvas nd-ui nd-clinical"><header><b>nadi / CLINICAL</b><span>PATIENT HANDOFF</span><i>DR</i></header><main><aside><div className="nd-patient"><span>ZA</span><b>Zainab Abdullahi<small>Age 11 · Passport current</small></b></div><nav><b className="on">OVERVIEW</b><b>TIMELINE</b><b>DOCUMENTS</b><b>ACCESS</b></nav><footer><small>NEXT REVIEW</small><b>Today · 14:30</b></footer></aside><section><header><div><small>SINCE LAST REVIEW / 24 AUGUST</small><h2>Two events. One open question.</h2></div><button>Open full record ↗</button></header><div className="nd-handoff"><article className="coral"><span>FAMILY NOTE · 26 AUG</span><b>Tiredness reported after school sports.</b><small>No clinical label added</small></article><article><span>DOCUMENT · 29 AUG</span><b>Referral letter uploaded by family.</b><small>PDF · 2 pages</small></article><article className="wide"><span>FAMILY QUESTION</span><b>“What should the school know before sports day next month?”</b></article></div><footer><span>Passport access confirmed with parent</span><button>Begin review →</button></footer></section></main></div>;
 return <div className="ui-canvas nd-ui nd-passport"><header><b>nadi</b><span>ZAINAB’S PASSPORT</span><button>Access & privacy</button></header><main><section><small>GOOD AFTERNOON</small><h2>Everything current,<br/>in one calm place.</h2><div className="nd-next"><span>NEXT CARE REVIEW</span><b>03 September · 2:30 PM</b><em>Paediatric Haematology Unit</em><button>Prepare for visit →</button></div></section><aside><div className="nd-current"><header><small>CARE PASSPORT</small><span>● CURRENT</span></header><h3>Zainab Abdullahi</h3><p>Last reviewed with Dr. Ibrahim<br/>24 August 2026</p><div><article><small>CARE TEAM</small><b>3 contacts</b></article><article><small>ACTIVE PASSES</small><b>1 school</b></article></div><button>Open passport →</button></div><div className="nd-timeline"><small>RECENT</small><p><i>29</i><b>Clinic letter added<span>By you · 10:14</span></b></p><p><i>26</i><b>School note recorded<span>Visible to care team</span></b></p></div></aside></main></div>;
}

function MorrowCover(){return <div className="ui-canvas mo-cover"><header><b>MORROW</b><span>THE ATTENDANCE FUND / 2026</span></header><main><section><small>ONE COMPLETE FUNDRAISING WEBSITE</small><h2>STAY<br/><em>IN</em><br/>SCHOOL.</h2><p>Practical support for the costs that quietly interrupt a girl’s education.</p></section><aside><div className="mo-cover-mark">08</div><div className="mo-cover-costs"><span>TRANSPORT</span><span>BOOKS</span><span>EXAMS</span><span>UNIFORM</span></div><footer><b>FROM NAVIGATION<br/>TO FOOTER</b><i>↘︎</i></footer></aside></main></div>}

function Told({kind}:{kind:string}){
 if(kind==="told-setup")return <div className="ui-canvas td-ui td-setup"><aside><b>TOLD</b><span>NEW CONVERSATION</span><ol><li className="done">01 Person</li><li className="active">02 Prompts</li><li>03 Access</li><li>04 Ready</li></ol><small>Private family archive</small></aside><main><header><span>Conversation with Aunty Rabi</span><button>Save and leave</button></header><section><small>THREE PROMPTS ARE ENOUGH</small><h2>Give the conversation<br/>somewhere to begin.</h2><div className="td-prompts"><article><span>01</span><p>What did home feel like when you were ten?</p><button>×</button></article><article><span>02</span><p>Who made you laugh the most growing up?</p><button>×</button></article><article><span>03</span><p>What do you wish we had asked your mother?</p><button>×</button></article></div><footer><button>＋ Add a prompt</button><button className="next">Continue to access →</button></footer></section></main></div>;
 if(kind==="told-record")return <div className="ui-canvas td-ui td-record"><header><b>TOLD / RECORDING ROOM</b><span>AUNTY RABI · HAUSA</span><i>FAMILY ONLY</i></header><main><section><small>CURRENT PROMPT</small><h2>What did home<br/>feel like when<br/>you were ten?</h2><button>Show next prompt →</button></section><aside><div className="td-rec-time"><span>● RECORDING</span><b>18:42</b><small>Tap the flag when a moment needs context.</small></div><div className="td-wave">{[24,51,34,72,43,65,29,81,55,38,69,45,77,31,59,88,42,68].map((n,i)=><i style={{height:`${n}%`}} key={i}/>)}</div><footer><button>⚑ Mark moment</button><button className="pause">Ⅱ</button><button>Finish recording</button></footer></aside></main></div>;
 if(kind==="told-archive")return <div className="ui-canvas td-ui td-archive"><header><b>TOLD</b><nav>PEOPLE&nbsp;&nbsp; CHAPTERS&nbsp;&nbsp; PLACES</nav><button>＋ Record a story</button></header><main><section><small>THE MUHAMMAD FAMILY ARCHIVE</small><h2>67 stories,<br/>still speaking.</h2><div className="td-filters"><span>All</span><span>Childhood</span><span>Home</span><span>Firsts</span></div></section><aside><article className="lead"><div>AR</div><small>AUNTY RABI · 18 MIN</small><h3>The blue house in Kano</h3><p>“We knew everybody on the street…”</p></article><article><div>YU</div><small>YA USMAN · 09 MIN</small><h3>The first journey south</h3></article><article><div>HA</div><small>HAJARA · 22 MIN</small><h3>Three wedding songs</h3></article></aside></main></div>;
 if(kind==="told-reader")return <div className="ui-canvas td-ui td-reader"><aside><b>TOLD</b><span>STORY 031 / FAMILY ONLY</span><div className="td-person">AR</div><small>TOLD BY</small><h3>Aunty Rabi</h3><p>Recorded in Abuja<br/>27 August 2026</p><button>View person →</button></aside><main><header><span>CHAPTER / HOME</span><button>•••</button></header><h2>The blue house<br/>in Kano</h2><article><p>We knew everybody on the street. Not just their names—what time they opened the gate, who made the best kunu, who would send you home if the sun had gone down.</p><p>There was a blue house opposite ours. I cannot remember the number now, but I remember the sound of the metal door.</p></article><div className="td-player"><button>▶</button><span><i/></span><b>06:18 / 18:42</b></div><footer><span>TRANSCRIPT REVIEWED BY SPEAKER</span><em>ACCESS · 12 FAMILY MEMBERS</em></footer></main></div>;
 return <div className="ui-canvas td-ui td-landing"><header><b>TOLD</b><nav>Why voices&nbsp;&nbsp; How it works&nbsp;&nbsp; Privacy</nav><button>Start a family archive</button></header><main><section><small>A PRIVATE HOME FOR FAMILY VOICES</small><h2>Keep the story.<br/><em>Not just the file.</em></h2><p>Guided conversations, careful context and family-controlled access—kept together for whoever comes next.</p><div><button>Hear how it works →</button><span>Voice · transcript · photographs · permission</span></div></section><aside><div className="td-land-story"><span>STORY 031 / HOME</span><b>The blue house<br/>in Kano</b><small>Told by Aunty Rabi · 18 min</small><div className="td-land-wave">{[2,4,3,6,4,8,5,7,3,6,4,7].map((n,i)=><i key={i} style={{height:`${n*7}px`}}/>)}</div></div><footer><i>AR</i><span>One voice.<br/>All its context.</span><b>↘︎</b></footer></aside></main></div>;
}

export function ProductMock({project,kind}:{project:Project;kind?:string}){
 const screen=kind||project.screens[0].kind;
 if(["hire-landing","site-landing","nara-landing","gona-landing","nadi-landing","told-landing","roam-home"].includes(screen)||(project.slug==="told"&&!kind))return <LandingPreview slug={project.slug}/>;
 if(project.slug==="hirewise")return <Hirewise kind={screen}/>;
 if(project.slug==="mahli")return <Mahli kind={screen}/>;
 if(project.slug==="sitecheck")return <SiteCheck kind={screen}/>;
 if(project.slug==="nara")return <Nara kind={screen}/>;
 if(project.slug==="roam")return <Roam kind={screen}/>;
 if(project.slug==="gona")return <GonaDistinct kind={screen}/>;
 if(project.slug==="nadi")return <NadiDistinct kind={screen}/>;
 if(project.slug==="morrow")return <MorrowCover/>;
 return <ToldDistinct kind={screen}/>;
}
